`timescale 1 ns/100 ps
// Version: v11.8 11.8.0.26


module RSA_64b_RAM(
       DINA,
       DOUTA,
       DINB,
       DOUTB,
       ADDRA,
       ADDRB,
       RWA,
       RWB,
       BLKA,
       BLKB,
       CLKAB,
       RESET
    );
input  [31:0] DINA;
output [31:0] DOUTA;
input  [31:0] DINB;
output [31:0] DOUTB;
input  [6:0] ADDRA;
input  [6:0] ADDRB;
input  RWA;
input  RWB;
input  BLKA;
input  BLKB;
input  CLKAB;
input  RESET;

    wire VCC, GND;
    wire GND_power_net1;
    wire VCC_power_net1;
    assign GND = GND_power_net1;
    assign VCC = VCC_power_net1;
    
    RAM4K9 #( .MEMORYFILE("RSA_64b_RAM_R0C2.mem") )  RSA_64b_RAM_R0C2 
        (.ADDRA11(GND), .ADDRA10(GND), .ADDRA9(GND), .ADDRA8(GND), 
        .ADDRA7(GND), .ADDRA6(ADDRA[6]), .ADDRA5(ADDRA[5]), .ADDRA4(
        ADDRA[4]), .ADDRA3(ADDRA[3]), .ADDRA2(ADDRA[2]), .ADDRA1(
        ADDRA[1]), .ADDRA0(ADDRA[0]), .ADDRB11(GND), .ADDRB10(GND), 
        .ADDRB9(GND), .ADDRB8(GND), .ADDRB7(GND), .ADDRB6(ADDRB[6]), 
        .ADDRB5(ADDRB[5]), .ADDRB4(ADDRB[4]), .ADDRB3(ADDRB[3]), 
        .ADDRB2(ADDRB[2]), .ADDRB1(ADDRB[1]), .ADDRB0(ADDRB[0]), 
        .DINA8(GND), .DINA7(DINA[23]), .DINA6(DINA[22]), .DINA5(
        DINA[21]), .DINA4(DINA[20]), .DINA3(DINA[19]), .DINA2(DINA[18])
        , .DINA1(DINA[17]), .DINA0(DINA[16]), .DINB8(GND), .DINB7(
        DINB[23]), .DINB6(DINB[22]), .DINB5(DINB[21]), .DINB4(DINB[20])
        , .DINB3(DINB[19]), .DINB2(DINB[18]), .DINB1(DINB[17]), .DINB0(
        DINB[16]), .WIDTHA0(VCC), .WIDTHA1(VCC), .WIDTHB0(VCC), 
        .WIDTHB1(VCC), .PIPEA(VCC), .PIPEB(VCC), .WMODEA(VCC), .WMODEB(
        VCC), .BLKA(BLKA), .BLKB(BLKB), .WENA(RWA), .WENB(RWB), .CLKA(
        CLKAB), .CLKB(CLKAB), .RESET(RESET), .DOUTA8(), .DOUTA7(
        DOUTA[23]), .DOUTA6(DOUTA[22]), .DOUTA5(DOUTA[21]), .DOUTA4(
        DOUTA[20]), .DOUTA3(DOUTA[19]), .DOUTA2(DOUTA[18]), .DOUTA1(
        DOUTA[17]), .DOUTA0(DOUTA[16]), .DOUTB8(), .DOUTB7(DOUTB[23]), 
        .DOUTB6(DOUTB[22]), .DOUTB5(DOUTB[21]), .DOUTB4(DOUTB[20]), 
        .DOUTB3(DOUTB[19]), .DOUTB2(DOUTB[18]), .DOUTB1(DOUTB[17]), 
        .DOUTB0(DOUTB[16]));
    RAM4K9 #( .MEMORYFILE("RSA_64b_RAM_R0C1.mem") )  RSA_64b_RAM_R0C1 
        (.ADDRA11(GND), .ADDRA10(GND), .ADDRA9(GND), .ADDRA8(GND), 
        .ADDRA7(GND), .ADDRA6(ADDRA[6]), .ADDRA5(ADDRA[5]), .ADDRA4(
        ADDRA[4]), .ADDRA3(ADDRA[3]), .ADDRA2(ADDRA[2]), .ADDRA1(
        ADDRA[1]), .ADDRA0(ADDRA[0]), .ADDRB11(GND), .ADDRB10(GND), 
        .ADDRB9(GND), .ADDRB8(GND), .ADDRB7(GND), .ADDRB6(ADDRB[6]), 
        .ADDRB5(ADDRB[5]), .ADDRB4(ADDRB[4]), .ADDRB3(ADDRB[3]), 
        .ADDRB2(ADDRB[2]), .ADDRB1(ADDRB[1]), .ADDRB0(ADDRB[0]), 
        .DINA8(GND), .DINA7(DINA[15]), .DINA6(DINA[14]), .DINA5(
        DINA[13]), .DINA4(DINA[12]), .DINA3(DINA[11]), .DINA2(DINA[10])
        , .DINA1(DINA[9]), .DINA0(DINA[8]), .DINB8(GND), .DINB7(
        DINB[15]), .DINB6(DINB[14]), .DINB5(DINB[13]), .DINB4(DINB[12])
        , .DINB3(DINB[11]), .DINB2(DINB[10]), .DINB1(DINB[9]), .DINB0(
        DINB[8]), .WIDTHA0(VCC), .WIDTHA1(VCC), .WIDTHB0(VCC), 
        .WIDTHB1(VCC), .PIPEA(VCC), .PIPEB(VCC), .WMODEA(VCC), .WMODEB(
        VCC), .BLKA(BLKA), .BLKB(BLKB), .WENA(RWA), .WENB(RWB), .CLKA(
        CLKAB), .CLKB(CLKAB), .RESET(RESET), .DOUTA8(), .DOUTA7(
        DOUTA[15]), .DOUTA6(DOUTA[14]), .DOUTA5(DOUTA[13]), .DOUTA4(
        DOUTA[12]), .DOUTA3(DOUTA[11]), .DOUTA2(DOUTA[10]), .DOUTA1(
        DOUTA[9]), .DOUTA0(DOUTA[8]), .DOUTB8(), .DOUTB7(DOUTB[15]), 
        .DOUTB6(DOUTB[14]), .DOUTB5(DOUTB[13]), .DOUTB4(DOUTB[12]), 
        .DOUTB3(DOUTB[11]), .DOUTB2(DOUTB[10]), .DOUTB1(DOUTB[9]), 
        .DOUTB0(DOUTB[8]));
    RAM4K9 #( .MEMORYFILE("RSA_64b_RAM_R0C0.mem") )  RSA_64b_RAM_R0C0 
        (.ADDRA11(GND), .ADDRA10(GND), .ADDRA9(GND), .ADDRA8(GND), 
        .ADDRA7(GND), .ADDRA6(ADDRA[6]), .ADDRA5(ADDRA[5]), .ADDRA4(
        ADDRA[4]), .ADDRA3(ADDRA[3]), .ADDRA2(ADDRA[2]), .ADDRA1(
        ADDRA[1]), .ADDRA0(ADDRA[0]), .ADDRB11(GND), .ADDRB10(GND), 
        .ADDRB9(GND), .ADDRB8(GND), .ADDRB7(GND), .ADDRB6(ADDRB[6]), 
        .ADDRB5(ADDRB[5]), .ADDRB4(ADDRB[4]), .ADDRB3(ADDRB[3]), 
        .ADDRB2(ADDRB[2]), .ADDRB1(ADDRB[1]), .ADDRB0(ADDRB[0]), 
        .DINA8(GND), .DINA7(DINA[7]), .DINA6(DINA[6]), .DINA5(DINA[5]), 
        .DINA4(DINA[4]), .DINA3(DINA[3]), .DINA2(DINA[2]), .DINA1(
        DINA[1]), .DINA0(DINA[0]), .DINB8(GND), .DINB7(DINB[7]), 
        .DINB6(DINB[6]), .DINB5(DINB[5]), .DINB4(DINB[4]), .DINB3(
        DINB[3]), .DINB2(DINB[2]), .DINB1(DINB[1]), .DINB0(DINB[0]), 
        .WIDTHA0(VCC), .WIDTHA1(VCC), .WIDTHB0(VCC), .WIDTHB1(VCC), 
        .PIPEA(VCC), .PIPEB(VCC), .WMODEA(VCC), .WMODEB(VCC), .BLKA(
        BLKA), .BLKB(BLKB), .WENA(RWA), .WENB(RWB), .CLKA(CLKAB), 
        .CLKB(CLKAB), .RESET(RESET), .DOUTA8(), .DOUTA7(DOUTA[7]), 
        .DOUTA6(DOUTA[6]), .DOUTA5(DOUTA[5]), .DOUTA4(DOUTA[4]), 
        .DOUTA3(DOUTA[3]), .DOUTA2(DOUTA[2]), .DOUTA1(DOUTA[1]), 
        .DOUTA0(DOUTA[0]), .DOUTB8(), .DOUTB7(DOUTB[7]), .DOUTB6(
        DOUTB[6]), .DOUTB5(DOUTB[5]), .DOUTB4(DOUTB[4]), .DOUTB3(
        DOUTB[3]), .DOUTB2(DOUTB[2]), .DOUTB1(DOUTB[1]), .DOUTB0(
        DOUTB[0]));
    RAM4K9 #( .MEMORYFILE("RSA_64b_RAM_R0C3.mem") )  RSA_64b_RAM_R0C3 
        (.ADDRA11(GND), .ADDRA10(GND), .ADDRA9(GND), .ADDRA8(GND), 
        .ADDRA7(GND), .ADDRA6(ADDRA[6]), .ADDRA5(ADDRA[5]), .ADDRA4(
        ADDRA[4]), .ADDRA3(ADDRA[3]), .ADDRA2(ADDRA[2]), .ADDRA1(
        ADDRA[1]), .ADDRA0(ADDRA[0]), .ADDRB11(GND), .ADDRB10(GND), 
        .ADDRB9(GND), .ADDRB8(GND), .ADDRB7(GND), .ADDRB6(ADDRB[6]), 
        .ADDRB5(ADDRB[5]), .ADDRB4(ADDRB[4]), .ADDRB3(ADDRB[3]), 
        .ADDRB2(ADDRB[2]), .ADDRB1(ADDRB[1]), .ADDRB0(ADDRB[0]), 
        .DINA8(GND), .DINA7(DINA[31]), .DINA6(DINA[30]), .DINA5(
        DINA[29]), .DINA4(DINA[28]), .DINA3(DINA[27]), .DINA2(DINA[26])
        , .DINA1(DINA[25]), .DINA0(DINA[24]), .DINB8(GND), .DINB7(
        DINB[31]), .DINB6(DINB[30]), .DINB5(DINB[29]), .DINB4(DINB[28])
        , .DINB3(DINB[27]), .DINB2(DINB[26]), .DINB1(DINB[25]), .DINB0(
        DINB[24]), .WIDTHA0(VCC), .WIDTHA1(VCC), .WIDTHB0(VCC), 
        .WIDTHB1(VCC), .PIPEA(VCC), .PIPEB(VCC), .WMODEA(VCC), .WMODEB(
        VCC), .BLKA(BLKA), .BLKB(BLKB), .WENA(RWA), .WENB(RWB), .CLKA(
        CLKAB), .CLKB(CLKAB), .RESET(RESET), .DOUTA8(), .DOUTA7(
        DOUTA[31]), .DOUTA6(DOUTA[30]), .DOUTA5(DOUTA[29]), .DOUTA4(
        DOUTA[28]), .DOUTA3(DOUTA[27]), .DOUTA2(DOUTA[26]), .DOUTA1(
        DOUTA[25]), .DOUTA0(DOUTA[24]), .DOUTB8(), .DOUTB7(DOUTB[31]), 
        .DOUTB6(DOUTB[30]), .DOUTB5(DOUTB[29]), .DOUTB4(DOUTB[28]), 
        .DOUTB3(DOUTB[27]), .DOUTB2(DOUTB[26]), .DOUTB1(DOUTB[25]), 
        .DOUTB0(DOUTB[24]));
    GND GND_power_inst1 (.Y(GND_power_net1));
    VCC VCC_power_inst1 (.Y(VCC_power_net1));
    
endmodule

// _Disclaimer: Please leave the following comments in the file, they are for internal purposes only._


// _GEN_File_Contents_

// Version:11.8.0.26
// ACTGENU_CALL:1
// BATCH:T
// FAM:PA3SOC2
// OUTFORMAT:Verilog
// LPMTYPE:LPM_RAM
// LPM_HINT:DUAL
// INSERT_PAD:NO
// INSERT_IOREG:NO
// GEN_BHV_VHDL_VAL:F
// GEN_BHV_VERILOG_VAL:F
// MGNTIMER:F
// MGNCMPL:T
// DESDIR:N:/Git/locknet373/smartfusion/lockNET_SF/smartgen\RSA_64b_RAM
// GEN_BEHV_MODULE:F
// SMARTGEN_DIE:IP4X3M1
// SMARTGEN_PACKAGE:fg484
// AGENIII_IS_SUBPROJECT_LIBERO:T
// WWIDTH:32
// WDEPTH:128
// RWIDTH:32
// RDEPTH:128
// CLKS:1
// CLOCK_PN:CLKAB
// RESET_PN:RESET
// RESET_POLARITY:0
// INIT_RAM:T
// DEFAULT_WORD:0x00000000
// CASCADE:0
// WCLK_EDGE:RISE
// WMODE1:1
// WMODE2:1
// PMODE1:1
// PMODE2:1
// DATAA_IN_PN:DINA
// DATAA_OUT_PN:DOUTA
// ADDRESSA_PN:ADDRA
// RWA_PN:RWA
// BLKA_PN:BLKA
// DATAB_IN_PN:DINB
// DATAB_OUT_PN:DOUTB
// ADDRESSB_PN:ADDRB
// RWB_PN:RWB
// BLKB_PN:BLKB
// WE_POLARITY:0
// RE_POLARITY:0
// PTYPE:2

// _End_Comments_

